default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  timeout: 5000

development:
  <<: *default
  database: vuebnb_development
  pool: 5
  username: chefy_api
  password: password

test:
  <<: *default
  database: vuebnb_test
  pool: 5
  username: chefy_api
  password: password

production:
  <<: *default
  database: vuebnb_production
  pool: 25
  username: root
  password: password